### ISSUE TITLE
GPU Crash

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/hrm-vita#1]
Hi Rinne, how are you? I was testing this new port, and after playing for a while... the gpu crashed. It happened after I progressed through 7 levels and wanted to go back to a previous one to review the game mechanics. There it crashed.
I have all plugins installed (except fdfix as I use repatch) and I did not use overclock (60 FPS stable almost all of the time). When I started the port again it crashed again after a while of playing. About 15 minutes... Am I doing something wrong?
Thanks in advance!

PS. Attached is an illustrative photo of the crash (I couldn't take my own photo because both times my console turned off).

![image](https://user-images.githubusercontent.com/70182567/225428297-a70ae37b-70b0-4b36-895d-37d25a8b561e.png)

**Comment by CatoTheYounger97** [comment]
Hello, I've playtested till level 15 in a 1hr+ play session without any crashes or restarts. It's possible your plugin setup or some other issue may be causing this behaviour.

**Comment by SofyUchiha** [comment]
> Hello, I've playtested till level 15 in a 1hr+ play session without any crashes or restarts. It's possible your plugin setup or some other issue may be causing this behaviour.

even when starting previous levels? (already passed).
Anyway, I provide a copy of my config.txt to rule out a possible conflict, for what it's worth. All plugins are updated to the latest version, with the exception of repatch which is version 2.71. 
Aslo a copy of the coredump.


[config.txt](https://github.com/Rinnegatamante/hrm-vita/files/10985292/config.txt)

[psp2core-1678909074-GPUCRASH.zip](https://github.com/Rinnegatamante/hrm-vita/files/10992195/psp2core-1678909074-GPUCRASH.zip)

**Comment by Cimmerian-Iter** [comment]
You have way too much plugins acting at once. 

I would try this config first with minimal plugin setup active and see if the issue still exist for you


[config.txt](https://github.com/Rinnegatamante/hrm-vita/files/10993319/config.txt)

**Comment by Rinnegatamante** [comment]
Give a try at this build: https://rinnegatamante.it/HRM_debug.vpk

**Comment by SofyUchiha** [comment]
> Give a try at this build: https://rinnegatamante.it/HRM_debug.vpk

Works fine, this and 1.2 version. Thanks so much!
