### ISSUE TITLE
(NP-6182-7) an error has occurred. Could not prepare the application to start.

### ISSUE THREAD

**Issue by Haasman0** [Rinnegatamante/hrm-vita#2]
It only happens when I boot the game with NoTrpDrm enabed, but when it is disabled, it works fine.

**Comment by Rinnegatamante** [comment]
Pushed an hotfix, reinstall the vpk and it should be fine.

**Comment by Haasman0** [comment]
Thanks. You are a big help to this community:)

**Comment by Haasman0** [comment]
Thanks Rinn, you are a big help to the PS Vita homebrew scene:)
________________________________
