### ISSUE TITLE
part of controller is unresponsive?

### ISSUE THREAD

**Issue by probablynotcereal** [Rinnegatamante/hrm-vita#4]
hello! not quite sure what files youd need from me here but on my vita i can only play this with the touch screen and buttons SQUARE, X, and START. neither joysticks nor dpad function at all. i can still play it perfectly with just the touch screen but i figured i would let you know of this?

**Comment by Rinnegatamante** [comment]
The game has no controller support.

**Comment by probablynotcereal** [comment]
oh ok, the "controls binding" part of the readme just confused me i guess

**Comment by Rinnegatamante** [comment]
Welp, those are just comfort controls i manually mapped to simulate dedicate touch presses but the game natively has only touch inputs.
